<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = 'Verificación en dos pasos de Google';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = 'Verificación en dos pasos';

$labels['secret'] = 'Secreto';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'Puedes añadir un <i>secreto</i> generado en tu ordenador con <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> y usarlo';

$labels['show_secret'] = 'Ver secreto';
$labels['hide_secret'] = 'Ocultar secreto';
$labels['create_secret'] = 'Crear secreto';

$labels['show_qr_code'] = 'Ver QR';
$labels['hide_qr_code'] = 'Ocultar QR';

$labels['recovery_codes'] = 'Códigos de recuperación';
$labels['show_recovery_codes'] = 'Ver códigos de recuperación';
$labels['hide_recovery_codes'] = 'Ocultar códigos de recuperación';

$labels['setup_all_fields'] = 'Configurar todos los campos (necesita Guardar)';

$labels['enrollment_dialog_title'] = 'Verificación en dos pasos de Google';
$labels['enrollment_dialog_msg'] = 'Está activada la <strong>Verificación en dos pasos</strong> por seguridad, es obligatoria iniciar sesión';

$labels['check_code'] = 'Comprobar código';
$labels['code_ok'] = 'Codigo correcto';
$labels['code_ko'] = 'Codigo erróneo';

$labels['dont_ask_me_30days'] = 'No solicitar códigos en este ordenador durante 30 días';

$labels['check_code_to_activate'] = 'Para guardar, debes comprobar con el código generado por Google Authenticator';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Datos han sido guardados correctamente.';
